### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by KostiantynRosokhatyi** [KostiantynRosokhatyj/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by KristianoMendes** [comment]
<h2>Resume</h2>      
                        <p><strong>Hi! I am an experienced energetic detective</strong> &mdash; with 2 years of experience finding bad guys. 
                          I try to find all the bad guys and kick their asses.</p>
