### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by KostiantynRosokhatyi** [KostiantynRosokhatyj/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by KostiantynRosokhatyj** [comment]
<h3>Experience</h3>
              <ul class="timeline">
                <li>
                  <p>2020</p>
                  <p>Became a film actor and starred in the film <i>"Detective Pikachu".</i></p>
                </li>
                <li>
                  <p>2018-2020</p>
                  <p>Developed a program with management personnel at banks to successfully prepare for a robbery.</p>
                </li>
                <li>
                  <p>2016-2018</p>
                  <p>Investigated theft related crimes including residential, commercial, auto-theft, vandalism,
                    fraud/forgeries and identity theft.</p>
                </li>
                <li>
                  <p>2014-2016</p>
                  <p>Developed a game <i>"Pokemon Go"</i></p>
                </li>
              </ul>
              <h3>Personal Life</h3>
              <ul class="timeline">
                <li>
                  <p>2008</p>
                  <p>Lost in a battle with a Pokemon like me.</p>
                </li>
                <li>
                  <p>2007</p>
                  <p>Met a new Pokemon <i>Bulbazaur</i>.</p>
                </li>
                <li>
                  <p>2006</p>
                  <p>Met <i>Ash</i> and became friends with him.</i></p>
                </li>
</ul>

**Comment by KristianoMendes** [comment]
<h3>Experience</h3>
              <ul class="timeline">
                <li>
                  <p>2020</p>
                  <p>Became a film actor and starred in the film <i>"Detective Pikachu".</i></p>
                </li>
                <li>
                  <p>2018-2020</p>
                  <p>Developed a program with management personnel at banks to successfully prepare for a robbery.</p>
                </li>
                <li>
                  <p>2016-2018</p>
                  <p>Investigated theft related crimes including residential, commercial, auto-theft, vandalism,
                    fraud/forgeries and identity theft.</p>
                </li>
                <li>
                  <p>2014-2016</p>
                  <p>Developed a game <i>"Pokemon Go"</i></p>
                </li>
              </ul>
              <h3>Personal Life</h3>
              <ul class="timeline">
                <li>
                  <p>2008</p>
                  <p>Lost in a battle with a Pokemon like me.</p>
                </li>
                <li>
                  <p>2007</p>
                  <p>Met a new Pokemon <i>Bulbazaur</i>.</p>
                </li>
                <li>
                  <p>2006</p>
                  <p>Met <i>Ash</i> and became friends with him.</i></p>
                </li>
</ul>
