### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by KostiantynRosokhatyi** [KostiantynRosokhatyj/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by KristianoMendes** [comment]
<section>
                <h3>Languages</h3>
                <p class="tags small"><span class="language" lang="en">&#x1f1fa;&#x1f1f8; English</span></p>
              </section>
              
              <section>
                <h3>Skills</h3>
                <p class="tags small">Static(Ability) Lightning Rod(Ability)</p>
              </section>
              
              <section>
                <h3>Character</h3>
                <p class="tags small">Personality disorder</p>
              </section>
              
              <section>
                <h3>Likes&#x1f603;</h3>
                <p class="tags small">HIT BAD GUYS WITH THE LIGHTNING STRIKE</p>
              </section>
              
              <section>
                <h3>Dislikes&#x1f61e;</h3>
                <p class="tags small">WATER DOGS SHAWARMA</p>
              </section>
              
              <section>
                <h3>Education</h3>
                <p class="tags small"><span class="education"> <b>Pokepon school</b> &mdash; <i>Doctor of Philosophy</i></span></p>
</section>

**Comment by KostiantynRosokhatyi** [comment]
> ### Languages
> 🇺🇸 English
> 
> ### Skills
> Static(Ability) Lightning Rod(Ability)
> 
> ### Character
> Personality disorder
> 
> ### Likes😃
> HIT BAD GUYS WITH THE LIGHTNING STRIKE
> 
> ### Dislikes😞
> WATER DOGS SHAWARMA
> 
> ### Education
> Pokepon school — Doctor of Philosophy

Perfect
